FROM python:3.10-alpine

MAINTAINER tecnologia@scielo.org

COPY . /app
COPY development.ini-TEMPLATE /app/config.ini

WORKDIR /app

RUN pip install --upgrade pip
RUN pip install gunicorn

ENV ARTICLEMETA_SETTINGS_FILE=/app/config.ini

RUN python setup.py develop
