FROM python:3.10-alpine

MAINTAINER tecnologia@scielo.org

COPY . /app
COPY development.ini-TEMPLATE /app/config.ini
COPY requirements.txt . 

WORKDIR /app

RUN apk update && apk add --no-cache \
  build-base \
  git

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install pyramid_debugtoolbar \
    && pip install waitress 

ENV ARTICLEMETA_SETTINGS_FILE=/app/config.ini

RUN python setup.py develop

CMD ["pserve", "/app/config.ini"]